---
- name: Create cloud-init custom userdata file (inline content)
  copy:
    dest: "{{ proxmox_vm_templater_ci_user_data_file_path }}/{{ proxmox_vm_templater_ci_user_data_file_name }}"
    content: "{{ proxmox_vm_templater_ci_user_data_content }}"
  delegate_to: "{{ proxmox_vm_templater_delegate }}"
  when:
    - proxmox_vm_templater_ci_user_data_content is defined
- name: Create cloud-init custom userdata file (src file)
  copy:
    dest: "{{ proxmox_vm_templater_ci_user_data_file_path }}/{{ proxmox_vm_templater_ci_user_data_volume }}"
    src: "{{ proxmox_vm_templater_ci_user_data_src_file }}"
  delegate_to: "{{ proxmox_vm_templater_delegate }}"
  when:
    - proxmox_vm_templater_ci_user_data_src_file is defined
- name: Configure cloud-init options
  proxmox_kvm: "{{ proxmox_vm_templater_cloud_init_super_fact }}"
  delegate_to: "{{ proxmox_vm_templater_delegate }}"
