---
# tasks file for ansible-role-proxmox-template
- name: Include assertions
  include_tasks: "assertions.yml"
- name: Include facts tasks
  include_tasks: "facts.yml"
- name: Include requirements tasks
  include_tasks: "requirements.yml"
- name: Download base image
  get_url:
    url: "{{ proxmox_vm_templater_base_image_url }}"
    dest: "/tmp/{{ proxmox_vm_templater_base_image_name }}"
  delegate_to: "{{ proxmox_vm_templater_delegate }}"
- name: Include virt-customize.yml tasks
  include_tasks: "virt-customize.yml"
- name: Create Base VM
  proxmox_kvm:
    api_user: "root@pam" # Only root + password can create a VM.
    api_password: "{{ proxmox_vm_templater_root_user_password }}"
    api_host: "{{ proxmox_vm_templater_target_host }}"
    node: "{{ proxmox_vm_templater_target_node }}"
    name: "{{ proxmox_vm_templater_vm_hostname }}"
    vmid: "{{ proxmox_vm_templater_vm_id }}"
    update: false
    cores: "{{ proxmox_vm_templater_vm_cores }}"
    sockets: "{{ proxmox_vm_templater_vm_sockets }}"
    memory: "{{ proxmox_vm_templater_vm_memory }}"
    net: "{{ proxmox_vm_templater_vm_network }}"
    format: "{{ proxmox_vm_templater_vm_format }}"
    storage: "{{ proxmox_vm_templater_vm_storage }}"
    serial:
      serial0: "socket"
    vga: serial0
    state: present
    agent: true
  delegate_to: "{{ proxmox_vm_templater_delegate }}"
- name: Include base-image.yml tasks
  include_tasks: base-image.yml
- name: Include cloud-init.yml tasks
  include_tasks: cloud-init.yml
  when: proxmox_vm_templater_configure_ci
- name: Create template
  proxmox_kvm:
    api_token_id: "{{ proxmox_vm_templater_api_token_id }}"
    api_user: "{{ proxmox_vm_templater_api_user }}"
    api_token_secret: "{{ proxmox_vm_templater_api_token_secret }}"
    api_host: "{{ proxmox_vm_templater_target_host }}"
    node: "{{ proxmox_vm_templater_target_node }}"
    name: "{{ proxmox_vm_templater_vm_hostname }}"
    vmid: "{{ proxmox_vm_templater_vm_id }}"
    update: true
    template: true
  delegate_to: "{{ proxmox_vm_templater_delegate }}"
- name: Cleanup
  file:
    path: "/tmp/{{ proxmox_vm_templater_base_image_name }}"
    state: absent
  delegate_to: "{{ proxmox_vm_templater_delegate }}"
  when: proxmox_vm_templater_cleanup
