---
- name: "Install Python Requirements"
  ansible.builtin.package:
    name: "{{ pkg_var }}"
    state: present
  delegate_to: "{{ proxmox_vm_templater_delegate }}"
  with_items: "{{ proxmox_vm_templater_required_packages }}"
  loop_control:
    loop_var: "pkg_var"
- name: "Install Python Pacakge Requirements"
  ansible.builtin.pip:
    executable: pip3
    name: "{{ pip_var }}"
  delegate_to: "{{ proxmox_vm_templater_delegate }}"
  with_items: "{{ proxmox_vm_templater_required_pip_packages }}"
  loop_control:
    loop_var: "pip_var"
